### ISSUE TITLE
"TypeError: this.proxy.getTime is not a function"

### ISSUE THREAD

**Issue by hawkowl** [tobami/codespeed#196] opened 2016-03-21 03:05 UTC
I've just updated Twisted's codespeed instance and I'm running into this appearing in the console and nothing at http://speed.twistedmatrix.com/timeline/ loading. https://speed.python.org/timeline/ also seems to have this issue, when you select a benchmark.

traceback:

```
TypeError: this.proxy.getTime is not a function
ag.prototype.getTime()
 jquery.jqplot.min.js:3
h.jqplot.DateAxisRenderer.prototype.init()
 jqplot.dateAxisRenderer.min.js:3
w.prototype.init()
 jquery.jqplot.min.js:3
R/this.init()
 jquery.jqplot.min.js:3
L.jqplot()
 jquery.jqplot.min.js:3
renderMiniplot()
 timeline.js:189
render()
 timeline.js:218
v.Callbacks/l()
 jquery-1.8.3.min.js:2
v.Callbacks/c.fireWith()
 jquery-1.8.3.min.js:2
T()
 jquery-1.8.3.min.js:2
.send/r()
```

It seems to have happened in https://github.com/tobami/codespeed/commit/509b7d5c8b9fe98f00ca8d7bd3af63f3d90c1ba1 ?

**Comment by hawkowl** [comment] 2016-03-21 03:18
I've reverted to 9893b87de02bdc1ea6256207de5cc010b095b3a5 on speed.twistedmatrix.com and it works now.

**Comment by tobami** [comment] 2016-03-28 09:48
I can confirm that jQplot 1.0.8 fails. The latest release (0.10.1) has the previous version so it shouldn't have the problem. I assume you are using master?

`speed.python.org` displays the problem because they are using master, as they are making good use of Python 3 and Django 1.8 compat, added after the latest release.

**Comment by hawkowl** [comment] 2016-03-28 09:51
Hmm, I see that the 0.10.1 tag doesn't have the commits that break it - I looked at master and it looked like it did. I'll pin to 0.10.1, then.

I am trying to keep things up-to-date and we were updating from master for some reason :) Need to update it so we pip install, rather than clone it...

**Comment by tobami** [comment] 2016-03-28 10:40
Cool. I'm looking at fixing the issue (probably going to not use isoformat and instead make Python return Javascript friendly epoch timestamps). I'm also doing some more clean ups to flesh out Python 3 support so we can have a fresh release.

While we are at it, what kind of Python and Django version compatibility would you be happy with in the next release? Would Django 1.8 be OK for you? And I guess you still need Python 2.7?

**Comment by tobami** [comment] 2016-03-28 12:08
Fixed by 7355c3ba85721955c917cf587f28cb27aabf64ae.

The timeline should work on `master` now.

**Closed by tobami** 2016-03-28 12:08 UTC

**Comment by hawkowl** [comment] 2016-03-28 15:07
Thanks @tobami.

RE: Django and Python compat; I'd be fine with whatever Django, I'd prefer the latest or LTS purely for security update reasons, though. We still do use Python 2.7, and the server is a bit crusty, but there's no reason we couldn't move to Python 3 eventually... with Twisted porting a lot over, I'd like to start eating our own dogfood, if that makes sense :)

**Comment by tobami** [comment] 2016-04-03 10:31
Yeah, that makes sense :smile:
